In [1]:
import numpy as np

In [8]:
arr1= np.arange(1000000)

In [9]:
list1=list(range(1000000))

In [10]:
%time for _ in range(10): arr2=arr1*2

Wall time: 29 ms


In [11]:
%time for _ in range(10): list2=list1*2
%time for _ in range(10): list3=[x*2 for x in list1]

Wall time: 341 ms
Wall time: 1.07 s


In [12]:
import numpy as np

In [13]:
data = np.random.randn(2,3)

In [14]:
data

array([[ 0.99842971, -0.01662122,  0.37803448],
       [-0.1607424 , -1.47924521,  2.5407139 ]])

In [15]:
data*10

array([[  9.98429709,  -0.16621224,   3.78034479],
       [ -1.60742401, -14.79245205,  25.40713898]])

In [17]:
data+data

array([[ 1.99685942, -0.03324245,  0.75606896],
       [-0.3214848 , -2.95849041,  5.0814278 ]])

In [18]:
data.shape

(2, 3)

In [19]:
data.dtype

dtype('float64')

In [20]:
data1=[6,7.5]

In [21]:
arr1 = np.array(data1)

In [22]:
arr1

array([6. , 7.5])

In [23]:
data2=[[1,2],[3,4]]

In [24]:
arr2=np.array(data2)

In [25]:
arr2

array([[1, 2],
       [3, 4]])

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 2)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
np.zeros(2,3)

TypeError: data type not understood

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.empty((3,2,4))

array([[[1.39805382e-076, 1.39804329e-076, 5.98153662e-154,
         6.27200198e-061],
        [6.01334503e-154, 4.85787493e-033, 4.85787506e-033,
         5.98154240e-154]],

       [[6.27200198e-061, 2.43896764e-154, 1.48373026e-076,
         7.70926395e-043],
        [1.96933462e-259, 1.90446521e+214, 4.82406562e+228,
         6.01346953e-154]],

       [[6.22651684e+228, 2.21576943e+214, 8.96368245e+276,
         2.31261087e-152],
        [6.01346954e-154, 2.92021216e-014, 1.06318459e+248,
         8.50960111e-096]]])

In [35]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr1= np.array([1,2,3],dtype = np.float64)

In [37]:
arr2=np.array([1,2,3],dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [40]:
float_arr1=arr1.astype(np.int16)

In [41]:
float_arr1.dtype

dtype('int16')

In [43]:
arr = np.array([1.2,1.3])

In [44]:
arr.astype(np.int32)

array([1, 1])

In [45]:
num_str1=np.array(['1.2','1.3'],dtype=np.string_)

In [46]:
num_str1.astype(np.float64)

array([1.2, 1.3])

In [47]:
arr1=np.arange(10)

In [48]:
arr2=np.array(['1.0','1.2'],dtype=np.float64)

In [49]:
arr1.astype(arr2.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])